/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package authortyfile;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author vincasbat
 
 Netbeans formed window
 
 */
public class Langas extends javax.swing.JFrame {

    /**
     * Creates new form Langas
     */
    public Langas() {
       try{
            URL imgUrl = null;
        ImageIcon imgIcon = null;

        imgUrl = Langas.class.getResource("res/ico.gif");
        imgIcon = new ImageIcon(imgUrl);
        Image img = imgIcon.getImage();
        this.setIconImage(img);
        initComponents();
         setLocationRelativeTo(null);
       } catch (Exception e){ JOptionPane.showMessageDialog(this, e.getMessage());  }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        btnAuthorityLT = new javax.swing.JButton();
        btnAuthorityEP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnIpat = new javax.swing.JButton();
        btnNpar = new javax.swing.JButton();
        btnTpar = new javax.swing.JButton();
        btnContentFile = new javax.swing.JButton();
        txtIpat = new javax.swing.JTextField();
        txtNpar = new javax.swing.JTextField();
        txtTpar = new javax.swing.JTextField();
        btnIsvalyti = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEPlist = new javax.swing.JButton();

        jFileChooser1.setDialogTitle("Pasirinkite failą su paraiškų ir patentų sąrašu");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Authority File sudarymas");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Authority File sudarymas");

        btnAuthorityLT.setText("LT dokumentai");
        btnAuthorityLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorityLTActionPerformed(evt);
            }
        });

        btnAuthorityEP.setText("EP dokumentai");
        btnAuthorityEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorityEPActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Data Delivery Content File");
        jLabel2.setFocusTraversalPolicyProvider(true);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnIpat.setText("IPAT");
        btnIpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIpatActionPerformed(evt);
            }
        });

        btnNpar.setText("NPAR");
        btnNpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNparActionPerformed(evt);
            }
        });

        btnTpar.setText("TPAR");
        btnTpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTparActionPerformed(evt);
            }
        });

        btnContentFile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnContentFile.setText("Content File");
        btnContentFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContentFileActionPerformed(evt);
            }
        });

        btnIsvalyti.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIsvalyti.setForeground(new java.awt.Color(255, 0, 51));
        btnIsvalyti.setText("X");
        btnIsvalyti.setToolTipText("Išvalyti");
        btnIsvalyti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsvalytiActionPerformed(evt);
            }
        });

        jLabel3.setText("20161020v");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/authortyfile/res/vincasoft5.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        btnEPlist.setText("EP list");
        btnEPlist.setToolTipText("Išveda visų Europos patentų sąrašą į failą \"VisiEP.txt\"");
        btnEPlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEPlistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnIpat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAuthorityLT, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIpat)
                                    .addComponent(txtNpar)
                                    .addComponent(txtTpar)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnIsvalyti)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnContentFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAuthorityEP, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEPlist)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAuthorityLT)
                    .addComponent(btnAuthorityEP)
                    .addComponent(btnEPlist))
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIpat)
                    .addComponent(txtIpat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNpar)
                    .addComponent(txtNpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTpar)
                    .addComponent(txtTpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContentFile)
                    .addComponent(btnIsvalyti)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAuthorityLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorityLTActionPerformed
       
        
       DateFormat dateFormat = new SimpleDateFormat("yyyyMMdd");
Date date = new Date();
String gendata = dateFormat.format(date);
                   
                 
 AuthortyFile.sudarytiLT( AuthortyFile.getLTlist(), "authority_file_"+gendata+"_LT.xml");
   if(true)   return;  
        
        jFileChooser1.setCurrentDirectory(new java.io.File("."));
         jFileChooser1.setApproveButtonText("Pasirinkti");
           
    if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                File file = jFileChooser1.getSelectedFile();
                BufferedReader input = null;
                List<String> sar = new ArrayList<>();
                input = new BufferedReader(new FileReader(file.getAbsolutePath()));
                String line = null;
                while ((line = input.readLine()) != null) {
                    String docnum = line.trim();
                    sar.add(docnum);
                }
                
                
                
                
                AuthortyFile.sudarytiLT(sar, "authority_file_"+gendata+"_LT.xml");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Langas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Langas.class.getName()).log(Level.SEVERE, null, ex);
            }
         
         
    }
    }//GEN-LAST:event_btnAuthorityLTActionPerformed

    private void btnAuthorityEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorityEPActionPerformed

            
       DateFormat dateFormat = new SimpleDateFormat("yyyyMMdd");
Date date = new Date();
String gendata = dateFormat.format(date);
AuthorityEP.sudarytiEP( AuthorityEP.getEPlist(), "authority_file_"+gendata+"_EP.xml");
     
    }//GEN-LAST:event_btnAuthorityEPActionPerformed

    private void btnIpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIpatActionPerformed
        jFileChooser1.setCurrentDirectory(new java.io.File("."));
         jFileChooser1.setApproveButtonText("Pasirinkti IPAT");
     if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        ipat = jFileChooser1.getSelectedFile();
        txtIpat.setText(ipat.getAbsolutePath());
     }  else ipat = null;
  if(ipat!=null)    jFileChooser1.setCurrentDirectory(ipat.getParentFile());
    }//GEN-LAST:event_btnIpatActionPerformed

    private void btnNparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNparActionPerformed
      
         jFileChooser1.setApproveButtonText("Pasirinkti NPAR");
     if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        npar = jFileChooser1.getSelectedFile();
        txtNpar.setText(npar.getAbsolutePath());
     }  else npar = null;
    if(npar!=null)  jFileChooser1.setCurrentDirectory(npar.getParentFile());
    }//GEN-LAST:event_btnNparActionPerformed

    private void btnTparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTparActionPerformed
       jFileChooser1.setApproveButtonText("Pasirinkti TPAR");
     if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        tpar = jFileChooser1.getSelectedFile();
        txtTpar.setText(tpar.getAbsolutePath());
     } else tpar = null;
   if(tpar!=null)   jFileChooser1.setCurrentDirectory(tpar.getParentFile());
    }//GEN-LAST:event_btnTparActionPerformed

    private void btnIsvalytiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsvalytiActionPerformed
                ipat = null;
                npar = null;
                tpar = null;
                txtIpat.setText("");
                txtNpar.setText("");
                txtTpar.setText("");
          if (!sarasas.isEmpty())      sarasas.clear(); 
    }//GEN-LAST:event_btnIsvalytiActionPerformed

    private void btnContentFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContentFileActionPerformed
       if(ipat!=null){
          BufferedReader input = null;
        try {
            input = new BufferedReader(new FileReader(ipat));
            String line = null;

            while ((line = input.readLine()) != null) {

                if (Pattern.matches("^\\(11\\).*", line)) {
                    String docnum = line.substring(5, 9);
                    sarasas.add(docnum);
                    System.out.println(docnum);
                }
                
            } //while
        } catch (FileNotFoundException ex) {
            
        } catch (java.io.IOException ex) {
           
        }
       
System.out.println(sarasas.toString()); 
       } // ipat != null
       
   //  ---------------- paraiskos:------------    
       
    if(npar!=null){
        BufferedReader input = null;
        try {
            input = new BufferedReader(new FileReader(npar));
            String line = null;

            while ((line = input.readLine()) != null) {

                if (Pattern.matches("^\\(21\\).*", line)) {
                    String docnum = line.substring(5, 13);
                    //    docnum = docnum.substring(0, 4) + " " + docnum.substring(4);
                    sarasas.add(docnum);
                    System.out.println(docnum);
                }
                // System.out.println(line);    
            } //while
        } catch (FileNotFoundException ex) {
            //        Logger.getLogger(Forma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (java.io.IOException ex) {
            //        Logger.getLogger(Forma.class.getName()).log(Level.SEVERE, null, ex);
        }
     System.out.println(sarasas.toString());  
    }//if npar not null     
       
       //  -- tpar: ------
       if(tpar!=null){
        BufferedReader input = null;
        try {
            input = new BufferedReader(new FileReader(tpar));
            String line = null;

            while ((line = input.readLine()) != null) {

                if (Pattern.matches("^\\(21\\).*", line)) {
                    String docnum = line.substring(5, 13);
                    //    docnum = docnum.substring(0, 4) + " " + docnum.substring(4);
                    sarasas.add(docnum);
                    System.out.println(docnum);
                }
                
            } //while
        } catch (FileNotFoundException ex) {
            //        Logger.getLogger(Forma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (java.io.IOException ex) {
            //        Logger.getLogger(Forma.class.getName()).log(Level.SEVERE, null, ex);
        }
     System.out.println(sarasas.toString());  
    }//if
       

       
   Collections.sort(sarasas, new Comparator<String>() {
        @Override
        public int compare(String str2, String str1)
        {
            return  str2.compareTo(str1);
        }
    });    
       
       
       
       
   // Sudarome Content File XML:
       
    
     DateFormat dateFormat = new SimpleDateFormat("yyyyMMdd");
Date date = new Date();
String gendata = dateFormat.format(date);
                
                
                AuthortyFile.sudarytiLT(sarasas, "contentDelivery_"+gendata+"_LT.xml");  
       
    }//GEN-LAST:event_btnContentFileActionPerformed

    private void btnEPlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEPlistActionPerformed
        
            // TODO add your handling code here:
            List<String> list = AuthorityEP.getEPlist();
       Path newFilePath = Paths.get("VisiEP.txt");
       
        try {
       if (Files.exists(newFilePath)) {
                
                    Files.delete(newFilePath);
                    Files.createFile(newFilePath);
                
       } else { Files.createFile(newFilePath); }
      } catch (IOException ex) {
                    Logger.getLogger(Langas.class.getName()).log(Level.SEVERE, null, ex);
                } 
   
     
            
            
    for (String epat : list)   {
                try { 
                    Files.write(newFilePath, ("(11)\t"+epat+System.lineSeparator()).getBytes(), StandardOpenOption.APPEND);
                } catch (IOException ex) {
                    Logger.getLogger(Langas.class.getName()).log(Level.SEVERE, null, ex);
                }
    }     
            
  
             
            JOptionPane.showMessageDialog(null, "Darbas baigtas", "Valstybinis patentų biuras", JOptionPane.INFORMATION_MESSAGE);
      
    }//GEN-LAST:event_btnEPlistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Langas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Langas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Langas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Langas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Langas().setVisible(true);
            }
        });
    }

  
    private File ipat;
    private File npar;
    private File tpar;
    
   private List<String> sarasas = new ArrayList<>();
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuthorityEP;
    private javax.swing.JButton btnAuthorityLT;
    private javax.swing.JButton btnContentFile;
    private javax.swing.JButton btnEPlist;
    private javax.swing.JButton btnIpat;
    private javax.swing.JButton btnIsvalyti;
    private javax.swing.JButton btnNpar;
    private javax.swing.JButton btnTpar;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtIpat;
    private javax.swing.JTextField txtNpar;
    private javax.swing.JTextField txtTpar;
    // End of variables declaration//GEN-END:variables
}
